
function EEG = pop_sereega_lftoggle(EEG)

cb_button_remove = [ ...
        'EEG.etc.sereega = rmfield(EEG.etc.sereega, ''leadfield'');', ...
        'close(gcbf);'];
cb_button_regenerate = [ ...
        'eval([''EEG.etc.sereega.leadfield = '' EEG.etc.sereega.leadfieldfunction]);', ...
        'close(gcbf);'];

if isfield(EEG.etc.sereega, 'leadfieldfunction')
    if isfield(EEG.etc.sereega, 'leadfield')
        buttontext = 'Remove lead field';
        buttoncallback = cb_button_remove;
    elseif ~isfield(EEG.etc.sereega, 'leadfield') || isempty(EEG.etc.sereega.leadfield)
        buttontext = 'Re-generate lead field';
        buttoncallback = cb_button_regenerate;
    end
else
    error('lead field re-generation code not available');
end

supergui( ...
        'geomhoriz', { 1 1 1 1 1 1 1 1 1 1 1 }, ...
        'geomvert', [1 1 1 1 1 1 1 1 1 1 1], ...
        'uilist', { ...
                { 'style', 'text', 'string', 'Remove/add lead field', 'fontweight', 'bold' }, ...
                { }, ...
                { 'style', 'text', 'string', 'A lead field can take up hundreds of megabytes' }, ...
                { 'style', 'text', 'string', 'and does not need to be saved with each simulated' }, ...
                { 'style', 'text', 'string', 'data set, as it can be re-generated when needed.' }, ...
                { }, ...
                { 'style', 'text', 'string', 'Press the below button to remove an included lead' }, ...
                { 'style', 'text', 'string', 'field before saving the data set, or to re-generate' }, ...
                { 'style', 'text', 'string', 'a lead field that was removed.' }, ...
                { }, ...
                { 'style', 'pushbutton', 'string', buttontext, 'callback', buttoncallback }, ...
                }, ... 
        'title', 'Lead field inclusion');

end

