
function EEG = pop_sereega_lf_generate_fromfieldtrip(EEG)

% strjoin is problematically overloaded by a number of EEGLAB toolboxes;
% making sure that we use the correct one
cdorig = cd(fileparts(which('strfun/strjoin')));
joinstring = @strjoin;
cd(cdorig);

% reading channel labels
labels = {};
fid = fopen('chanlocs-standard_1005.elp','r'); 
while ~feof(fid)
    line = fgets(fid);
    [i, j] = regexp(line, '(?<=EEG\s+)\w+(?=\s)');
    if ~isempty(i), labels = [labels, {line(i:j)}]; end
end
fclose(fid);
labels = setdiff(labels, {'RPA', 'LPA', 'Nz'});
labels = sort(labels);

% getting montages
montages = {sprintf('All %d channels', length(labels)), 'Custom selection'};
montages = [montages, utl_get_montage('?')];

% callbacks
cb_montage = [ ...
        'if get(gcbo, ''value'') == 1', ...
        '    set(findobj(''parent'', gcbf, ''tag'', ''labeledit''), ''string'', ''' joinstring(labels) ''');' ...
        'elseif get(gcbo, ''value'') == 2', ...
        '    set(findobj(''parent'', gcbf, ''tag'', ''labeledit''), ''string'', '''');' ...
        'else', ...
        '    montage = get(gcbo, ''String'');', ...
        '    montage = montage(get(gcbo, ''value''));', ...
        '    set(findobj(''parent'', gcbf, ''tag'', ''labeledit''), ''string'', joinstring(utl_get_montage(montage{1})));' ...
        'end'];
cb_select = [ ...
        '[~, labelselection] = pop_chansel({''' joinstring(labels, ''',''') '''});' ...
        'if ~isempty(labelselection)' ...
        '    set(findobj(''parent'', gcbf, ''tag'', ''labeledit''), ''string'', labelselection);' ...
        'end'];

[~, ~, ~, structout] = inputgui( ...
        'geometry', { 1 1 1 1 1 1 1 1 1 [4 1] }, ...
        'geomvert', [1 1 1 1 1 1 1 6 1 1], ...
        'uilist', { ...
                { 'style', 'text', 'string', 'Obtain a lead field using FieldTrip', 'fontweight', 'bold' }, ...
                { }, ...
                { 'style', 'text', 'string', 'Indicate the resolution of the grid in mm' }, ...
                { 'style', 'edit', 'string', '10', 'tag', 'resolution' }, ...
                { }, ...
                { 'style', 'text', 'string', 'Indicate which channels to include in the simulation,' }, ...
                { 'style', 'text', 'string', 'using a montage or custom channel selection' }, ...
                { 'style', 'listbox', 'string', montages, 'tag', 'montage', 'callback', cb_montage }, ...
                { }, ...
                { 'style', 'edit', 'string', joinstring(labels), 'tag', 'labeledit' }, ...
                { 'style', 'pushbutton', 'string', '...', 'callback', cb_select } }, ... 
        'helpcom', 'pophelp(''lf_generate_fromfieldtrip'');', 'title', 'Lead field: FieldTrip');

if ~isempty(structout)
    % user pressed OK, getting label selection in cell format
    labelselection = textscan(structout.labeledit, '%s');
    labelselection = labelselection{1}';
    
    % adding lead field to EEG structure
    EEG.etc.sereega.leadfield = lf_generate_fromfieldtrip('resolution', str2num(structout.resolution), 'labels', labelselection);
    
    % also adding code to generate lead field
    EEG.etc.sereega.leadfieldfunction = sprintf('lf_generate_fromfieldtrip(''resolution'', %s, ''labels'', %s);', structout.resolution, ['{''' joinstring(labelselection, ''',''') '''}']);
end

end

