
function EEG = pop_sereega_epochs(EEG)

[~, ~, ~, structout] = inputgui( ...
        'geometry', { 1 1 [1 1] [1 1] [1 1] 1 [1 1] [1 1]}, ...
        'geomvert', [1 1 1 1 1 1 1 1], ...
        'uilist', { ...
                { 'style', 'text', 'string', 'Configure epochs', 'fontweight', 'bold' }, ...
                { }, ...
                { 'style', 'text', 'string', 'Number of epochs' }, ...
                { 'style', 'edit', 'string', '100', 'tag', 'n' }, ...
                { 'style', 'text', 'string', 'Length (ms)' }, ...
                { 'style', 'edit', 'string', '1000', 'tag', 'length' }, ...
                { 'style', 'text', 'string', 'Sampling rate (Hz)' }, ...
                { 'style', 'edit', 'string', '1000', 'tag', 'srate' }, ...
                { }, ...
                { 'style', 'text', 'string', 'Event marker' }, ...
                { 'style', 'edit', 'string', 'event', 'tag', 'marker' }, ...
                { 'style', 'text', 'string', 'Prestimulus period (ms)' }, ...
                { 'style', 'edit', 'string', '0', 'tag', 'prestim' }, ...
                }, ... 
        'title', 'Epoch configuration');

if ~isempty(structout)
    % user pressed OK
    epochs = struct(...
        'n', str2num(structout.n), ...
        'length', str2num(structout.length), ...
        'srate', str2num(structout.srate), ...
        'marker', structout.marker, ...
        'prestim', str2num(structout.prestim));
    
    EEG.etc.sereega.epochs = epochs;
end

end

